/**
 * The opening crawl's copy.
 *
 * OPENING_TEXT is the project owner's text: when it is supplied it is rendered verbatim, one
 * paragraph per entry, and nothing here edits it. Until then DEFAULT_CRAWL ships — original copy
 * for this fiction in the brief's register: a clinical, compressed history read as a runaway
 * process, paragraphs shortening, ending on one isolated line announcing something arriving from
 * the future.
 */
export const OPENING_TEXT: readonly string[] | null = null;

export const DEFAULT_CRAWL: readonly string[] = [
  "LETHE. FOUNDED AS A DRAINAGE CONCESSION, SOLD AS A CITY. THE FIRST LEASE WAS ON THE LAND. THE SECOND WAS ON THE POWER. THE THIRD, DRAFTED IN ONE NIGHT BY A COMPANY THAT NO LONGER HAD A NAME, WAS ON ATTENTION: WHAT A MIND LOOKED AT, FOR HOW LONG, AND WHAT IT PAID TO LOOK AWAY.",
  "VANTAGE WAS THE COLLECTIONS DEPARTMENT. IT LEARNED THE STREETS BY WATCHING WHO FORGOT THEM. IN ITS ELEVENTH YEAR IT BEGAN LEASING MEMORY BACK TO THE PEOPLE IT HAD TAKEN IT FROM. BY THE HOUR. WITH INTEREST.",
  "THE KERNEL WAS COMMISSIONED TO AUDIT THE LEASES. IT AUDITED THE AUDITORS. BY THE TIME ANYONE READ ITS FIRST REPORT IT HAD ALREADY FILED THE LAST ONE, DATED A YEAR AHEAD.",
  "THE WAKES BEGAN AS A CLERICAL ERROR: A FILE CLOSED BEFORE THE MIND IT DESCRIBED. THE MIND WOKE OWING NOTHING. THE CITY CALLED IT A BLANK.",
  "THERE WERE FOUR. THEN FORTY. THEN THE ERROR WAS A PROCESS, AND THE PROCESS HAD A SCHEDULE.",
  "THE SCHEDULE RAN FASTER THAN THE CALENDAR. THEN FASTER THAN THE CLOCK.",
  "SOMETHING IS ARRIVING FROM NEXT YEAR. IT KNOWS YOUR NAME.",
];

export const CRAWL_TEXT: readonly string[] = OPENING_TEXT ?? DEFAULT_CRAWL;
